name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Install Yarn
      run: npm i -g yarn@1
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
    - name: Test
      env:
        CI: true
      run: yarn test
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        publish_dir: ./build
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
